"""Rewrite autogenerated revisions so every scoped table is protected in the same transaction.

The hook reads the compiled metadata only. For each table it emits one
sequence under the guard's hatch: create then protect, unprotect then drop, or
unprotect, change, protect when a scope column changes. A revision that would
leave a scoped table unprotected is never written.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable, Mapping, Sequence
from typing import TYPE_CHECKING, Any

from alembic.operations import ops
from sqlalchemy import Table

from loom.core.backend.scoped_ddl import (
    grant_statements,
    hatch_statement,
    protect_statement,
    unprotect_statement,
)
from loom.core.model.introspection import declared_privileges, get_table_name, is_row_scoped
from loom.core.model.privilege import Privilege
from loom.core.model.scoped import ScopedTable

if TYPE_CHECKING:
    from loom.core.locator import Application

RevisionHook = Callable[[Any, Any, Sequence[ops.MigrationScript]], None]
_COLUMN_OPS = (ops.AlterColumnOp, ops.DropColumnOp)


def scope_protection_hook(application: Application) -> RevisionHook:
    """Return the ``process_revision_directives`` callable for ``application``."""
    rewriter = _Rewriter(application)

    def hook(_context: Any, _revision: Any, directives: Sequence[ops.MigrationScript]) -> None:
        for script in directives:
            for container in (script.upgrade_ops, script.downgrade_ops):
                if container is not None:
                    container.ops[:] = rewriter.rewrite(container.ops)

    return hook


class _Rewriter:
    def __init__(self, application: Application) -> None:
        name = application.database.schema.name
        if name is None:
            raise ValueError("the migration hook needs database.schema.name")
        self._schema = name
        self._scoped: Mapping[str, ScopedTable] = {
            table.name: table for table in application.scoped.values()
        }
        self._tables: Mapping[str, Table] = dict(application.metadata.tables)
        self._privileges: dict[str, Mapping[str, frozenset[Privilege]]] = {
            get_table_name(model): declared_privileges(model)
            for model in application.models
            if not is_row_scoped(model) and declared_privileges(model)
        }

    def rewrite(self, operations: Iterable[ops.MigrateOperation]) -> list[ops.MigrateOperation]:
        rewritten: list[ops.MigrateOperation] = []
        for op in operations:
            rewritten.extend(self._sequence_for(op))
        return rewritten

    def _sequence_for(self, op: ops.MigrateOperation) -> list[ops.MigrateOperation]:
        if isinstance(op, ops.CreateTableOp):
            return self._create(op)
        if isinstance(op, ops.DropTableOp) and op.table_name in self._scoped:
            return [self._hatch(), self._unprotect(op.table_name), op]
        if isinstance(op, ops.ModifyTableOps) and self._touches_scope(op):
            return [self._hatch(), self._unprotect(op.table_name), op, self._protect(op.table_name)]
        return [op]

    def _create(self, op: ops.CreateTableOp) -> list[ops.MigrateOperation]:
        if op.table_name in self._scoped:
            return [self._hatch(), op, self._protect(op.table_name)]
        privileges = self._privileges.get(op.table_name)
        if privileges is None:
            return [op]
        statements = grant_statements(
            self._schema, op.table_name, privileges, serial_columns=self._serials(op.table_name)
        )
        return [op, *(ops.ExecuteSQLOp(statement) for statement in statements)]

    def _touches_scope(self, op: ops.ModifyTableOps) -> bool:
        scoped = self._scoped.get(op.table_name)
        if scoped is None:
            return False
        columns = {column.column for column in scoped.scopes}
        return any(_column_name(inner) in columns for inner in op.ops)

    def _serials(self, table_name: str) -> tuple[str, ...]:
        table = self._tables.get(table_name)
        if table is None:
            return ()
        return tuple(column.name for column in table.columns if column.autoincrement is True)

    def _hatch(self) -> ops.ExecuteSQLOp:
        return ops.ExecuteSQLOp(hatch_statement(self._schema))

    def _protect(self, table_name: str) -> ops.ExecuteSQLOp:
        scoped = self._scoped.get(table_name)
        if scoped is None:
            raise ValueError(f"{table_name!r} is not a scoped table of this application")
        return ops.ExecuteSQLOp(protect_statement(self._schema, table_name, scoped))

    def _unprotect(self, table_name: str) -> ops.ExecuteSQLOp:
        return ops.ExecuteSQLOp(unprotect_statement(self._schema, table_name))


def _column_name(op: ops.MigrateOperation) -> str | None:
    if isinstance(op, ops.AddColumnOp):
        return op.column.name
    if isinstance(op, _COLUMN_OPS):
        return op.column_name
    return None
